kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: arm64

steps:
- name: publish
  image: thegeeklab/drone-docker-buildx
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  debug: true
  platforms: linux/arm64,linux/amd64
  settings:
    repo: shanduur/ddgo
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

