kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: arm64

steps:
- name: publish
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    platforms:
      - linux/arm64
      - linux/amd64
    repo: shanduur/ddgo
    tags: [ "${DRONE_COMMIT_SHA:0:7}", "latest" ]
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
