kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: arm64

trigger:
  event:
    include:
    - push
    - pull_request

steps:
- name: publish
  image: thegeeklab/drone-docker-buildx
  # privileged: true
  # volumes:
  # - name: docker
  #   path: /var/run/docker.sock
  settings:
    platforms:
      - linux/arm64
      - linux/amd64
    repo: shanduur/ddgo
    tags: [ "${DRONE_COMMIT_SHA:0:7}", "latest" ]
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

services:
  - name: dind
    image: docker:dind
    privileged: true

# volumes:
# - name: docker
#   host:
#     path: /var/run/docker.sock

